---
# Sets passwords for system users
# Note: Wherever possible public keys should be used instead of passwords

# Python crypt code modified from:
# http://serverfault.com/questions/330069/how-to-create-an-sha-512-hashed-password-for-shadow

- name: generate password hashes
  shell: "python -c \"import crypt,random,string; print crypt.crypt('{{ item.password }}', ''.join([random.choice(string.ascii_letters + string.digits) for _ in range(16)]))\""
  when: item.password is defined
  with_items: "{{ system_users_users }}"
  register: system_users_fact_hashed_user_passwords
  changed_when: false

- name: set user password using password hash
  user:
    name="{{ item.0.username }}"
    password="{{ item.1.stdout }}"
  when: item.0.password is defined
  with_together:
    - "{{ system_users_users }}"
    - "{{ system_users_fact_hashed_user_passwords.results }}"
