---
# Manages operating system users

- name: manage system user
  user:
       name="{{ item.username }}"
        uid="{{ item.uid     | default(omit) }}"
    comment="{{ item.comment | default(omit) }}"
      shell="{{ item.shell   | default(omit) }}"
      state="{{ item.state   | default(omit) }}"
  with_items: system_users_users
